CREATE SCHEMA FISHCOMPANY;

CREATE TABLE FISHCOMPANY.Customer(
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    company VARCHAR(20) NOT NULL,
    city VARCHAR(20) NOT NULL,
    street VARCHAR(20) NOT NULL,
    buildingNum VARCHAR(10) NOT NULL,
    phoneNum VARCHAR(10) NOT NULL,
    account VARCHAR(15) NOT NULL,
    percentPaym DOUBLE NOT NULL,
    debt DOUBLE NOT NULL,
    login VARCHAR(20) NOT NULL,
    password VARCHAR(150) NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO FISHCOMPANY.Customer(company,city,street,buildingNum,
phoneNum,account,percentPaym,debt,login,password)
values ('Magnoliya','Kyiv','Pecherskaya','12a','0631561747','3456782',100.00,0.0,'povchin','enter567');
INSERT INTO FISHCOMPANY.Customer(company,city,street,buildingNum,
phoneNum,account,percentPaym,debt,login,password)
values ('Edelveys','Lviv','Baydykova','15','0672504765','567890123',50.00,0.0,'ddayneko','log96789');
INSERT INTO FISHCOMPANY.Customer(company,city,street,buildingNum,
phoneNum,account,percentPaym,debt,login,password)
values ('DemAlyans','Simferopol','Rosiyskaya','12','0981551654','64687890',70.00,0.0'dpetrovskiy','dpetr709912');

Select * from FISHCOMPANY.Customer;

UPDATE FISHCOMPANY.Customer
SET FISHCOMPANY.CUSTOMER.PASSWORD='mzSeKzj38lmZ9rZIT9FqNxzw3Fr0CoZV'
WHERE FISHCOMPANY.CUSTOMER.LOGIN LIKE 'povchin';

UPDATE FISHCOMPANY.Customer
SET FISHCOMPANY.CUSTOMER.DEBT=20.00
WHERE FISHCOMPANY.CUSTOMER.LOGIN LIKE 'povchin';



CREATE TABLE FISHCOMPANY.Staff(
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    firstName VARCHAR(20) NOT NULL,
    lastName VARCHAR(20) NOT NULL,
    city VARCHAR(20) NOT NULL,
    street VARCHAR(20) NOT NULL,
    buildingNum VARCHAR(10) NOT NULL,
    phoneNum VARCHAR(10) NOT NULL,
    position VARCHAR(20) NOT NULL,
    login VARCHAR(20) NOT NULL,
    password VARCHAR(100) NOT NULL,
    status CHAR(1) NOT NULL,
    comments VARCHAR(100),
    PRIMARY KEY (id)
);

INSERT INTO FISHCOMPANY.Staff(firstName,lastName,city,street,buildingNum,phoneNum,position,login,
password,status,comments)
values ('system','system','Kyiv','Amosova','12a','0445456812','system','system','mzSeKzj38lmZ9rZIT9FqNxzw3Fr0CoZV','A','Automate  Processes');

UPDATE FISHCOMPANY.Staff
SET FISHCOMPANY.STAFF.PASSWORD='mzSeKzj38lmZ9rZIT9FqNxzw3Fr0CoZV'
WHERE FISHCOMPANY.STAFF.LOGIN LIKE 'amalchenko';
DELETE FROM FISHCOMPANY.Staff
WHERE FISHCOMPANY.Staff.id=4; 

INSERT INTO FISHCOMPANY.Staff(firstName,lastName,city,street,buildingNum,phoneNum,position,login,
password,status,comments)
values ('Nikolay','Komarov','Kyiv','Saburova','12','0682124516','Accountant','NKomar','kode550','A',NULL);
INSERT INTO FISHCOMPANY.Staff(firstName,lastName,city,street,buildingNum,phoneNum,position,login,
password,status,comments)
values ('Natalya','Shvedova','Nikolaev','Simferopolskaya','12','0672127654','Manager','shvedova','entrance200','A',NULL);
INSERT INTO FISHCOMPANY.Staff(firstName,lastName,city,street,buildingNum,phoneNum,position,login,
password,status,comments)
values ('Leonid','Yaschuk','Odessa','Fontanskaya','24','0632105567','Store Manager','Lyaschuk','mzSeKzj38lmZ9rZIT9FqNxzw3Fr0CoZV','A',NULL);

Select * from FISHCOMPANY.Staff;

UPDATE FISHCOMPANY.STAFF
SET FISHCOMPANY.STAFF.POSITION = 'storemanager'
WHERE FISHCOMPANY.STAFF.ID = 8;



CREATE TABLE FISHCOMPANY.GeneralFishOrder(
	id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	orderedWeight DOUBLE NOT NULL,
	orderNum VARCHAR(15) NOT NULL,
	orderStatus CHAR(1) DEFAULT 'N',
	PRIMARY KEY (id)
);

INSERT INTO FISHCOMPANY.GeneralFishOrder(orderedWeight,orderNum,orderStatus) 
values (10000.00,'567854','N');
INSERT INTO FISHCOMPANY.GeneralFishOrder(orderedWeight,orderNum,orderStatus)  
values (20000.00,'123456','N');
INSERT INTO FISHCOMPANY.GeneralFishOrder(orderedWeight,orderNum,orderStatus) 
values (300000.00,'181876','Y');

Select * FROM FISHCOMPANY.GeneralFishOrder;

SELECT ID, ORDERNUM, ORDERSTATUS, ORDEREDWEIGHT, SHIPNAME FROM GENERALFISHORDER WHERE (ID = 1);


CREATE TABLE FISHCOMPANY.FishStore(
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    fishName VARCHAR(20) NOT NULL,
    warehouseWeight DOUBLE NOT NULL,
    idGenFishOrder INTEGER NOT NULL,
    deliveryDate DATE,
    orderedWeight DOUBLE NOT NULL,
    deliveredWeight DOUBLE NOT NULL,
    saleWeight DOUBLE NOT NULL,
    deliveryPrice DOUBLE NOT NULL,
    salePrice DOUBLE NOT NULL,
    writeOffWeight DOUBLE DEFAULT 0.00,
    comments VARCHAR(100),
    PRIMARY KEY (id),
    FOREIGN KEY (idGenFishOrder)
	REFERENCES FISHCOMPANY.GeneralFishOrder (id)
);

INSERT INTO FISHCOMPANY.FishStore(fishName,warehouseWeight,idGenFishOrder,deliveryDate,
orderedWeight,deliveredWeight,saleWeight,deliveryPrice,salePrice,writeOffWeight,comments) 
values ('Paltus',20000.00,1,NULL,100.00,0.00,100.00,150.00,120.00,0.00,NULL);
INSERT INTO FISHCOMPANY.FishStore(fishName,warehouseWeight,idGenFishOrder,deliveryDate,
orderedWeight,deliveredWeight,saleWeight,deliveryPrice,salePrice,writeOffWeight,comments)
values ('Forel',30000.00,2,'08.02.2015',200.00, 30000.00,2500.00,200.00,170.00,0.00,NULL);
INSERT INTO FISHCOMPANY.FishStore(fishName,warehouseWeight,idGenFishOrder,deliveryDate,
orderedWeight,deliveredWeight,saleWeight,deliveryPrice,salePrice,writeOffWeight,comments)
values ('Tolstolob',30000.00,3,'08.05.2015',300.00 3000.00,3000.00,80.00,290.00,0.00,NULL);
INSERT INTO FISHCOMPANY.FishStore(fishName,warehouseWeight,idGenFishOrder,deliveryDate,
orderedWeight,deliveredWeight,saleWeight,deliveryPrice,salePrice,writeOffWeight,comments) 
values ('Dorada',0.00,1,'08.05.2015',100.00,0.00,100.00,150.00,120.00,0.00,NULL);

Select * from FISHCOMPANY.FishStore;

UPDATE FISHCOMPANY.FishStore
SET FISHCOMPANY.FISHSTORE.DELIVEREDWEIGHT = 400.00
WHERE FISHCOMPANY.FISHSTORE.FISHNAME LIKE 'Dorada';

Select * from FISHCOMPANY.FishStore
WHERE FISHCOMPANY.FISHSTORE.SALEPRICE > 0
AND FISHCOMPANY.FISHSTORE.SALEWEIGHT > 0
AND FISHCOMPANY.FISHSTORE.DELIVERYDATE IS NOT NULL;

Select * from FISHCOMPANY.FishStore
WHERE FISHCOMPANY.FISHSTORE.DELIVEREDWEIGHT - FISHCOMPANY.FISHSTORE.WAREHOUSEWEIGHT  <= FISHCOMPANY.FISHSTORE.WAREHOUSEWEIGHT;


SELECT DISTINCT FISHCOMPANY.FISHSTORE.FISHNAME
FROM FISHCOMPANY.FishStore;


CREATE TABLE FISHCOMPANY.CustOrder(
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    orderNum VARCHAR(100) NOT NULL,
    customerId INTEGER NOT NULL,
    fishID INTEGER NOT NULL,
    weight DOUBLE NOT NULL,
    copySalePrice DOUBLE NOT NULL,
    orderDate Date NOT NULL,
    bankTransferedMoney DOUBLE DEFAULT 0.00,
    comments VARCHAR(100),
    PRIMARY KEY (id),
	FOREIGN KEY (customerId)
	REFERENCES FISHCOMPANY.Customer (id),
	FOREIGN KEY (fishId)
	REFERENCES FISHCOMPANY.FishStore (id)
);

INSERT INTO FISHCOMPANY.CustOrder(orderNum,customerId,fishID,weight,copySalePrice,orderDate,bankTransferedMoney,comments)
values (11,1,1,200.00,300.00,'21.09.2015',100.00,NULL);
INSERT INTO FISHCOMPANY.CustOrder(orderNum,customerId,fishID,weight,copySalePrice,orderDate,bankTransferedMoney,comments)
values (13,2,2,300.00,400.00,'24.09.2015',0.00,NULL);
INSERT INTO FISHCOMPANY.CustOrder(orderNum,customerId,fishID,weight,copySalePrice,orderDate,bankTransferedMoney,comments)
values (15,3,3,600.00,600.00,'29.09.2015',300.00,NULL);

Select FISHCOMPANY.CustOrder.orderNum from FISHCOMPANY.CustOrder
WHERE FISHCOMPANY.CUSTORDER.ORDERNUM LIKE '20151207223157c8b1a';

CREATE TABLE FISHCOMPANY.ConfirmedPayment(
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    orderNum VARCHAR(100) NOT NULL,
    stuffId INTEGER NOT NULL,
    copyPercentPaym DOUBLE NOT NULL,
    payedMoney DOUBLE DEFAULT 0.00,
    totalSumOrder DOUBLE NOT NULL,
    shipmentAvailable CHAR(1),
    comments VARCHAR(100),
    PRIMARY KEY (id),
	FOREIGN KEY (stuffId)
	REFERENCES FISHCOMPANY.Staff (id)
);

INSERT INTO FISHCOMPANY.ConfirmedPayment(orderNum, stuffId,copyPercentPaym,payedMoney,ShipmentAvailable,comments) 
values (11,1,100.00,0.00,'N',NULL);
INSERT INTO FISHCOMPANY.ConfirmedPayment(orderNum, stuffId,copyPercentPaym,ShipmentAvailable,comments) 
values (13,1,75.00,'N',NULL);
INSERT INTO FISHCOMPANY.ConfirmedPayment(orderNum, stuffId,copyPercentPaym,ShipmentAvailable,comments) 
values (15,1,50.00,'Y',NULL);

SELECT FISHCOMPANY.CUSTORDER.ORDERDATE FROM FISHCOMPANY.CUSTORDER
WHERE ORDERNUM = ANY
(SELECT FISHCOMPANY.CONFIRMEDPAYMENT.ORDERNUM from FISHCOMPANY.CONFIRMEDPAYMENT
WHERE FISHCOMPANY.CONFIRMEDPAYMENT.SHIPMENTAVAILABLE LIKE 'Y');


SELECT FISHCOMPANY.FISHSTORE.FISHNAME FROM FISHCOMPANY.FISHSTORE, FISHCOMPANY.CUSTORDER
WHERE FISHCOMPANY.CUSTORDER.FISHID = FISHCOMPANY.FISHSTORE.ID
AND ORDERNUM = ANY
(SELECT FISHCOMPANY.CONFIRMEDPAYMENT.ORDERNUM from FISHCOMPANY.CONFIRMEDPAYMENT
WHERE FISHCOMPANY.CONFIRMEDPAYMENT.SHIPMENTAVAILABLE LIKE 'Y');

SELECT FISHCOMPANY.CUSTORDER.ORDERDATE,SUM((FISHCOMPANY.CUSTORDER.COPYSALEPRICE * FISHCOMPANY.CUSTORDER.WEIGHT) - (FISHCOMPANY.FISHSTORE.DELIVERYPRICE * FISHCOMPANY.CUSTORDER.WEIGHT)) as income
FROM FISHCOMPANY.FISHSTORE, FISHCOMPANY.CUSTORDER
WHERE FISHCOMPANY.CUSTORDER.ORDERNUM = ANY
(SELECT FISHCOMPANY.CONFIRMEDPAYMENT.ORDERNUM from FISHCOMPANY.CONFIRMEDPAYMENT
WHERE FISHCOMPANY.CONFIRMEDPAYMENT.SHIPMENTAVAILABLE LIKE 'Y')
AND FISHCOMPANY.CUSTORDER.FISHID = FISHCOMPANY.FISHSTORE.ID
AND FISHCOMPANY.CUSTORDER.ORDERDATE BETWEEN '2014-08-01' AND '2015-12-31' 
AND FISHCOMPANY.CUSTORDER.ORDERNUM = ANY
(SELECT FISHCOMPANY.CONFIRMEDPAYMENT.ORDERNUM from FISHCOMPANY.CONFIRMEDPAYMENT
WHERE FISHCOMPANY.CONFIRMEDPAYMENT.SHIPMENTAVAILABLE LIKE 'Y')
GROUP BY ORDERDATE
ORDER BY income asc;

UPDATE FISHCOMPANY.FISHSTORE
SET FISHCOMPANY.FISHSTORE.DELIVERYPRICE = 100
WHERE FISHCOMPANY.FISHSTORE.ID = 1;





UPDATE FISHCOMPANY.CONFIRMEDPAYMENT
SET FISHCOMPANY.CONFIRMEDPAYMENT.SHIPMENTAVAILABLE = 'N'
WHERE FISHCOMPANY.CONFIRMEDPAYMENT.ID = 3;

SELECT FISHCOMPANY.CUSTORDER.ORDERDATE FROM FISHCOMPANY.CUSTORDER
WHERE ORDERNUM LIKE 
(SELECT FISHCOMPANY.CONFIRMEDPAYMENT.ORDERNUM from FISHCOMPANY.CONFIRMEDPAYMENT
WHERE FISHCOMPANY.CONFIRMEDPAYMENT.SHIPMENTAVAILABLE LIKE 'Y');

Select * from FISHCOMPANY.ConfirmedPayment
WHERE 
FISHCOMPANY.CONFIRMEDPAYMENT.PAYEDMONEY - FISHCOMPANY.CONFIRMEDPAYMENT.COPYPERCENTPAYM * FISHCOMPANY.CONFIRMEDPAYMENT.TOTALSUMORDER / 100 >= 0;

SELECT FISHCOMPANY.

SELECT FISHCOMPANY.FISHSTORE.FISHNAME, FISHCOMPANY.CUSTORDER.WEIGHT,
FISHCOMPANY.CUSTORDER.COPYSALEPRICE 
FROM FISHCOMPANY.CUSTORDER, FISHCOMPANY.FISHSTORE, FISHCOMPANY.CUSTOMER
WHERE
FISHCOMPANY.CUSTORDER.FISHID = FISHCOMPANY.FISHSTORE.ID
AND
FISHCOMPANY.CUSTORDER.CUSTOMERID = FISHCOMPANY.CUSTOMER.ID
AND FISHCOMPANY.CUSTOMER.COMPANY LIKE 'Magnoliya';

/*
 * Select what fish is Ordered
 */

SELECT FISHCOMPANY.CUSTORDER.ID, FISHCOMPANY.FISHSTORE.FISHNAME
FROM FISHCOMPANY.CUSTORDER, FISHCOMPANY.FISHSTORE
WHERE
FISHCOMPANY.CUSTORDER.FISHID = FISHCOMPANY.FISHSTORE.ID;


/*
 * Select borrows
 */
SELECT FISHCOMPANY.CUSTOMER.COMPANY,FISHCOMPANY.CUSTOMER.ACCOUNT,FISHCOMPANY.STAFF.FIRSTNAME,FISHCOMPANY.STAFF.LASTNAME,
FISHCOMPANY.STAFF.POSITION,FISHCOMPANY.CONFIRMEDPAYMENT.PERCENTPAYM
FROM FISHCOMPANY.CONFIRMEDPAYMENT, FISHCOMPANY.STAFF, FISHCOMPANY.CUSTOMER, FISHCOMPANY.CUSTORDER
WHERE
FISHCOMPANY.CONFIRMEDPAYMENT.STUFFID = FISHCOMPANY.STAFF.ID
AND
FISHCOMPANY.CONFIRMEDPAYMENT.FISHCOMPANYRORDERID = FISHCOMPANY.CUSTORDER.ID
AND
FISHCOMPANY.CUSTORDER.CUSTOMERID = FISHCOMPANY.CUSTOMER.ID
AND
FISHCOMPANY.CONFIRMEDPAYMENT.SHIPMENTAVAILABLE LIKE 'Y'
AND
FISHCOMPANY.CONFIRMEDPAYMENT.PERCENTPAYM < 100.00;
/*
 * Select fish for Sale
 */
SELECT FISHCOMPANY.FISHSTORE.FISHNAME,FISHCOMPANY.FISHSTORE.SALEWEIGHT,
FISHCOMPANY.FISHSTORE.SALEPRICE
FROM FISHCOMPANY.FISHSTORE
WHERE SALEPRICE > 0
AND SALEWEIGHT > 0
AND SALESTATUS LIKE 'Y'
AND WRITEOFFSTATUS LIKE 'N'
AND DELIVERYDATE IS NOT NULL;
AND ID = 2;
/*
 * Select what type fish in the order for Dispatcher
 */
SELECT FISHCOMPANY.CONFIRMEDPAYMENT.FISHCOMPANYRORDERID,FISHCOMPANY.FISHSTORE.FISHNAME,
FISHCOMPANY.CUSTORDER.WEIGHT
FROM FISHCOMPANY.CONFIRMEDPAYMENT,FISHCOMPANY.FISHSTORE, FISHCOMPANY.CUSTORDER
WHERE
FISHCOMPANY.CONFIRMEDPAYMENT.FISHCOMPANYRORDERID = FISHCOMPANY.CUSTORDER.ID
AND
FISHCOMPANY.CUSTORDER.FISHID = FISHCOMPANY.FISHSTORE.ID
AND
FISHCOMPANY.CONFIRMEDPAYMENT.SHIPMENTAVAILABLE LIKE 'Y';
/*
 * Select what type fish will be delivered on the ship for the cold store manager
 */
SELECT FISHCOMPANY.GENERALFISHORDER.SHIPNAME,FISHCOMPANY.FISHSTORE.FISHNAME,
FISHCOMPANY.GENERALFISHORDER.ORDEREDWEIGHT
FROM FISHCOMPANY.GENERALFISHORDER, FISHCOMPANY.FISHSTORE
WHERE
FISHCOMPANY.FISHSTORE.IDGENFISHORDER = FISHCOMPANY.GENERALFISHORDER.ID
AND DELIVERYDATE IS NULL;
/*
 * Generate report for income
 */
SELECT FISHCOMPANY.FISHSTORE.FISHNAME,FISHCOMPANY.CUSTORDER.ORDERDATE,
SUM(FISHCOMPANY.CUSTORDER.WEIGHT) AS WEIGHT,
SUM(FISHCOMPANY.CUSTORDER.COPYSALEPRICE) AS INCOME
FROM FISHCOMPANY.FISHSTORE,FISHCOMPANY.CUSTORDER,FISHCOMPANY.CONFIRMEDPAYMENT
WHERE
FISHCOMPANY.CUSTORDER.ID = FISHCOMPANY.CONFIRMEDPAYMENT.APPRORDERID
AND
FISHCOMPANY.FISHSTORE.ID = FISHCOMPANY.CUSTORDER.FISHID
AND
FISHCOMPANY.CONFIRMEDPAYMENT.SHIPMENTAVAILABLE LIKE 'Y'
AND FISHCOMPANY.CUSTORDER.ORDERDATE BETWEEN '2015-08-01' AND '2015-10-01'
GROUP BY FISHCOMPANY.FISHSTORE.FISHNAME,FISHCOMPANY.CUSTORDER.ORDERDATE;




ALTER TABLE FISHCOMPANY.Customer DROP COLUMN ID;
ALTER TABLE FISHCOMPANY.CustOrder DROP COLUMN ID;
ALTER TABLE FISHCOMPANY.CustOrder DROP COLUMN FISHID;
ALTER TABLE FISHCOMPANY.CustOrder DROP COLUMN CUSTOMERID;
ALTER TABLE FISHCOMPANY.Staff DROP COLUMN ID;
ALTER TABLE FISHCOMPANY.FishStore DROP COLUMN ID;
ALTER TABLE FISHCOMPANY.ConfirmedPayment DROP COLUMN ID;
ALTER TABLE FISHCOMPANY.GeneralFishOrder DROP COLUMN ID;


Drop Table FISHCOMPANY.Customer;
Drop Table FISHCOMPANY.FishStore;
Drop Table FISHCOMPANY.CustOrder;
Drop Table FISHCOMPANY.Staff;
Drop Table FISHCOMPANY.ConfirmedPayment;
Drop Table FISHCOMPANY.GeneralFishOrder;


DELETE FROM FISHCOMPANY.GeneralFishOrder
WHERE Id > 3;
DROP SCHEMA FISHCOMPANY RESTRICT;



/* 
 
 ALTER TABLE FISHCOMPANY.FISHCOMPANYrovedOrder DROP COLUMN ID;
 Drop Table FISHCOMPANY.FISHCOMPANYrovedOrders;
 
 ALTER TABLE FISHCOMPANY.AccountantPayments DROP COLUMN ID;
 Drop Table FISHCOMPANY.AccountantPayments;
 
 ALTER TABLE FISHCOMPANY.PaymentType DROP COLUMN ID;
 Drop Table FISHCOMPANY.PaymentType;
 
 
Drop Table FISHCOMPANY.DeliveryOrders;
 
CREATE TABLE FISHCOMPANY.Addresses(
    id INTEGER NOT NULL,
    country VARCHAR(20) NOT NULL,
    city VARCHAR(20) NOT NULL,
    street VARCHAR(20) NOT NULL,
    buildingNum VARCHAR(20) NOT NULL,
    PRIMARY KEY (id)
);



CREATE TABLE FISHCOMPANY.PaymentType(
	id INTEGER NOT NULL,
	payment VARCHAR(20) NOT NULL,
	PRIMARY KEY (id)
);






CREATE TABLE FISHCOMPANY.FISHCOMPANYrovedOrders(
    id INTEGER NOT NULL,
    orderId INTEGER NOT NULL,
    stuffId INTEGER NOT NULL,
    comments VARCHAR(100),
    PRIMARY KEY (id),
	FOREIGN KEY (orderId)
	REFERENCES FISHCOMPANY.Orders (id),
	FOREIGN KEY (stuffId)
	REFERENCES FISHCOMPANY.Staff (id)
);

CREATE TABLE FISHCOMPANY.DeliveryOrders(
    id INTEGER NOT NULL,
    confPayId INTEGER NOT NULL,
    deliveryDate DATE NOT NULL,
    comments VARCHAR(100),
    PRIMARY KEY (id),
	FOREIGN KEY (confPayId)
	REFERENCES FISHCOMPANY.ConfirmedPayments (id)
);

INSERT INTO FISHCOMPANY.DeliveryOrders values (1,1,'18.09.2015',NULL);
INSERT INTO FISHCOMPANY.DeliveryOrders values (2,3,'20.11.2015',NULL);
INSERT INTO FISHCOMPANY.DeliveryOrders values (3,1,'11.12.2015',NULL);

Select * from FISHCOMPANY.DeliveryOrders;

INSERT INTO FISHCOMPANY.Addresses values (1,'Ukraine','Kyiv','Solomenskaya','11a');
INSERT INTO FISHCOMPANY.Addresses values (2,'Ukraine','Kharkiv','Geroev Truda','48');
INSERT INTO FISHCOMPANY.Addresses values (3,'Ukraine','Zhytomyr','Kyivska','24b');
INSERT INTO FISHCOMPANY.Addresses values (4,'Ukraine','Lviv','Kopernica','26');

INSERT INTO FISHCOMPANY.PaymentType values (1,'Full Payment');
INSERT INTO FISHCOMPANY.PaymentType values (2,'Partialy Payment');
INSERT INTO FISHCOMPANY.PaymentType values (3,'Credit');

INSERT INTO FISHCOMPANY.AccountantPayments values (1,1,1,'Y',NULL);
INSERT INTO FISHCOMPANY.AccountantPayments values (2,2,2,'Y',NULL);
INSERT INTO FISHCOMPANY.AccountantPayments values (3,2,2,'N',NULL);

Select * from FISHCOMPANY.Addresses;
Select * from FISHCOMPANY.PaymentType;
Select * from FISHCOMPANY.FISHCOMPANYrovedOrders;

ALTER TABLE FISHCOMPANY.Addresses DROP COLUMN id;

Drop Table FISHCOMPANY.Addresses;
*/








/*
 * deliveryPrice is pointed for the 1kg. salePrice is pointed for 1kg. Need trigger 
 * for creation salary price according the rule (currentDate - deliveryDate)*constant*deliveryPrice
 * 
 */








/*
 * From Table Accountant payment must be selected for delivery only 
 * orders with status shipment Y. If N accountant must check againe.
 */


/*
 *Positiv  Delivery orders must be only if in FISHCOMPANYroved Orders table
 *status shipment is Y 
 */
